name: Deploy

on:
  schedule:
    -   cron: '30 2 * * 0' # # 对应 分 时 日 月 星期，30 23 * * *：每天 23:30 UTC（北京时间 7:30 第二天）北京时间 = UTC 时间 + 8 小时23 + 8 = 31-24=7
  workflow_dispatch:

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
